// server/tools/meta.js - 工具契约元数据（WS1；施工图 docs/tool-contracts-v1.md 转录）
// tier: core|pro|expert（toolDefs(expose) 过滤用；过滤只影响暴露不影响 execTool 执行）
// when/not/ex：拼进 function calling description，帮模型在正确时刻选对工具（X1 评审）
// 注意：conv_summarize 为 WS5 预留（尚未注册进 TOOLS），tier=pro
export const TOOL_META = {
  // ===== core(21) =====
  read_file: { tier: 'core', when: '读文本内容、改前先读、查实现细节', not: '大文件超限用 read_file_range；列目录用 list_dir', ex: 'read_file {path:"/srv/harness-workbench/server/agent.js"}' },
  read_file_range: { tier: 'core', when: '大文件按 offset/length 分段读', not: '小文件直接用 read_file', ex: 'read_file_range {path, offset:10000, length:5000}' },
  write_file: { tier: 'core', when: '新建文件或整体覆盖', not: '局部小改用 edit_file；追加用 append_file', ex: 'write_file {path, content}' },
  append_file: { tier: 'core', when: '文件末尾追加（日志/渐进内容）', not: '覆盖/创建用 write_file', ex: 'append_file {path, content}' },
  edit_file: { tier: 'core', when: '精确局部替换（old 需与文件内容唯一匹配）', not: '未先 read_file 不要盲改；大段重写用 write_file', ex: 'edit_file {path, old, new}' },
  list_dir: { tier: 'core', when: '列目录看结构、确认路径存在', not: '递归找文件用 find_file', ex: 'list_dir {path}' },
  mkdir: { tier: 'core', when: '创建目录', not: '创建文件用 write_file', ex: 'mkdir {path}' },
  copy_move: { tier: 'core', when: '复制或移动文件/目录', not: '删除用 delete_file', ex: 'copy_move {src, dst, mode:"copy"}' },
  find_file: { tier: 'core', when: '按文件名子串定位（免通配符）', not: '按内容搜索用 grep_search', ex: 'find_file {path, name:"agent.js"}' },
  grep_search: { tier: 'core', when: '按正则搜文件内容（代码/文本文件）', not: '按文件名用 find_file；查库用 db_query', ex: 'grep_search {path, pattern:"ensureRun"}' },
  web_search: { tier: 'core', when: '查外部新知/事实/时效信息', not: '查内部内容用 grep_search/db_query', ex: 'web_search {queries:["deepseek v4"]}' },
  fetch_url: { tier: 'core', when: '抓取指定网页正文', not: '找网页用 web_search', ex: 'fetch_url {url}' },
  syntax_check: { tier: 'core', when: 'JS 语法校验（改代码后必跑）', not: '跑测试套件用 run_test', ex: 'syntax_check {path}' },
  run_test: { tier: 'core', when: '运行项目测试套件', not: '单文件语法用 syntax_check', ex: 'run_test {dir}' },
  plan_tasks: { tier: 'core', when: '多步复杂任务先列清单（>3 步）', not: '单步小任务直接做', ex: 'plan_tasks {tasks:"步骤列表"}' },
  plan_done: { tier: 'core', when: '标记清单第 N 步已完成（从 1 开始）', not: '全部完成后用 finish_task 提测', ex: 'plan_done {index:1}' },
  finish_task: { tier: 'core', when: '提测：对照验收自检后提交"完成候选"', not: '未完成/未验证禁止调用', ex: 'finish_task {summary, selfCheck}' },
  ask_user: { tier: 'core', when: '需要用户拍板/方案选择', not: '可自行查证的事实不要问', ex: 'ask_user {question, options}' },
  set_goal: { tier: 'core', when: '用户要求持续推进的跨轮大目标', not: '一次性任务用 plan_tasks', ex: 'set_goal {objective}' },
  get_goal: { tier: 'core', when: '查看当前活动目标与进度', not: '—', ex: 'get_goal {}' },
  update_goal: { tier: 'core', when: '汇报目标进展/标记完成/放弃', not: '—', ex: 'update_goal {progress, status:"done"}' },
  // ===== pro(31) =====
  ocr_image: { tier: 'pro', when: '图片含文字需提取（截图/扫描件）', not: '图片理解用 view_image', ex: 'ocr_image {path}' },
  view_image: { tier: 'pro', when: '视觉理解图片内容', not: '纯文字提取用 ocr_image', ex: 'view_image {path}' },
  extract_pdf: { tier: 'pro', when: '解析 PDF 文本', not: '文本文件用 read_file', ex: 'extract_pdf {path}' },
  extract_docx: { tier: 'pro', when: '解析 Word 文本', not: '文本文件用 read_file', ex: 'extract_docx {path}' },
  extract_xlsx: { tier: 'pro', when: '解析 Excel 内容', not: '文本文件用 read_file', ex: 'extract_xlsx {path}' },
  extract_pptx: { tier: 'pro', when: '解析 PPT 文本', not: '文本文件用 read_file', ex: 'extract_pptx {path}' },
  db_query: { tier: 'pro', when: '只读查库（单条 SELECT；用量/会话/工具统计）', not: '写库用 db_write；SHOW/多语句不支持；表列结构先查 information_schema，勿猜列名', ex: 'db_query {sql:"SELECT COUNT(*) FROM usage_stats"}' },
  git_status: { tier: 'pro', when: '提交前查看工作区状态', not: '看提交历史用 run_command git log', ex: 'git_status {dir}' },
  git_commit: { tier: 'pro', when: '小步提交（自改纪律：改前先提交当前状态）', not: '未验证代码不提交', ex: 'git_commit {dir, message}' },
  git_branch: { tier: 'pro', when: '分支 list/create/checkout', not: '推送用 git_pull_push', ex: 'git_branch {dir, action:"list"}' },
  run_long_task: { tier: 'pro', when: '长命令后台执行不阻塞', not: '短命令用 run_command', ex: 'run_long_task {command}' },
  job_list: { tier: 'pro', when: '列出后台任务状态', not: '—', ex: 'job_list {}' },
  job_output: { tier: 'pro', when: '读后台任务输出（最近 8000 字符）', not: '已完成的结果在任务返回里', ex: 'job_output {jobId}' },
  subagent: { tier: 'pro', when: '委派独立子任务（隔离上下文）', not: '小查询自己做；批量用 subagent_fanout', ex: 'subagent {prompt, mode:"sync"}' },
  subagent_fork: { tier: 'pro', when: '子代理延续本会话上下文继续深挖', not: '全新任务用 subagent', ex: 'subagent_fork {prompt}' },
  subagent_fanout: { tier: 'pro', when: '同模板批量派发（{{item}} 占位）', not: '条目少时逐个做', ex: 'subagent_fanout {items, prompt}' },
  subagent_join: { tier: 'pro', when: '收口多个异步子代理结果', not: '单个结果用 subagent_output', ex: 'subagent_join {ids}' },
  subagent_output: { tier: 'pro', when: '取异步子代理结果（running/done）', not: '未完成可稍候重试或 join', ex: 'subagent_output {id}' },
  subagent_report: { tier: 'pro', when: '复盘/审计：取子代理全步骤明细', not: '只要结论用 subagent_output', ex: 'subagent_report {id}' },
  subagent_list: { tier: 'pro', when: '查看全部子代理状态（编排/排查）', not: '—', ex: 'subagent_list {}' },
  kb_add: { tier: 'pro', when: '沉淀"记住/以后都按…"（global 或本会话）', not: '复盘条目标题加"打回复盘:"前缀（度量）', ex: 'kb_add {title, body, scope:"global"}' },
  kb_search: { tier: 'pro', when: '找记忆/历史决策/用户偏好（先搜再用）', not: '—', ex: 'kb_search {q}' },
  kb_del: { tier: 'pro', when: '删除错误/过期记忆', not: '—', ex: 'kb_del {id}' },
  create_contract: { tier: 'pro', when: '立项：验收先成文，驱动器无人值守执行', not: '小任务或讨论中不要用', ex: 'create_contract {goal, acceptance, boundaries}' },
  skills_list: { tier: 'pro', when: '用户提"技能/方法"时先查可用技能', not: '已确定直接 skill_load', ex: 'skills_list {}' },
  skill_load: { tier: 'pro', when: '载入技能（全文入系统提示，会话内持续生效）', not: '一次性约定用 kb_add', ex: 'skill_load {name}' },
  skill_save: { tier: 'pro', when: '新建/更新技能（复盘结论固化）', not: '零散经验用 kb_add', ex: 'skill_save {name, description, body}' },
  ralph: { tier: 'pro', when: '难题多轮"全新视角"逼近（每轮无历史）', not: '常规任务别用（成本高）', ex: 'ralph {objective}' },
  feishu_doc_read: { tier: 'pro', when: '读飞书云文档/知识库内容', not: '非飞书用 fetch_url', ex: 'feishu_doc_read {url}' },
  feishu_sheet_read: { tier: 'pro', when: '读飞书电子表格', not: '—', ex: 'feishu_sheet_read {url, range}' },
  feishu_bitable_read: { tier: 'pro', when: '读飞书多维表格', not: '—', ex: 'feishu_bitable_read {appToken, tableId}' },
  conv_summarize: { tier: 'pro', when: '长会话收尾/跨周 resume 前归档摘要（WS5 注册）', not: '短会话不需要', ex: 'conv_summarize {}' },
  // ===== expert(9) =====
  delete_file: { tier: 'expert', when: '删除文件/目录（确认过；高危留痕）', not: '保留内容用 copy_move 移走', ex: 'delete_file {path}' },
  db_write: { tier: 'expert', when: '数据库写入/迁移（非 SELECT）', not: '读用 db_query；写前先 SELECT 复核影响面', ex: 'db_write {sql, params}' },
  git_pull_push: { tier: 'expert', when: '拉取/推送远程（push 前先 pull 防分叉）', not: '本地提交用 git_commit', ex: 'git_pull_push {dir, action:"push"}' },
  run_command: { tier: 'expert', when: '无专门工具覆盖的系统操作（npm/部署/systemctl）', not: 'cat/ls/grep/sed/head/tail/find/cd/echo 用专门工具', ex: 'run_command {command:"npm install"}' },
  kill_process: { tier: 'expert', when: '终止失控/废弃后台任务', not: '正常任务等它自己结束', ex: 'kill_process {jobId}' },
  reload_platform: { tier: 'expert', when: '自改代码生效（先 syntax_check+git commit）', not: '仅改配置/数据不需要', ex: 'reload_platform {}' },
  set_limits: { tier: 'expert', when: '用户要求调整护栏（0=不限；先解释再改）', not: '未经请求不要自行放宽', ex: 'set_limits {minutes:0}' },
  plan_mode: { tier: 'expert', when: '用户要求"先规划只读、别动手"', not: '普通任务不要进入', ex: 'plan_mode {}' },
  exit_plan_mode: { tier: 'expert', when: '规划查证完成，提交完整计划并退出只读', not: '未查证完不要提交', ex: 'exit_plan_mode {plan}' },
};

// 5.3c/5.4 默认工具启用集（harness 标准 25：日常开发/运维高频；其余在 设置→工具 按需勾选）
export const DEFAULT_TOOLSET = [
  'read_file', 'write_file', 'append_file', 'edit_file', 'list_dir', 'find_file', 'grep_search',
  'web_search', 'fetch_url',
  'run_command', 'syntax_check', 'run_test',
  'db_query', 'git_status', 'git_commit',
  'plan_tasks', 'plan_done', 'finish_task', 'ask_user', 'set_goal',
  'kb_add', 'kb_search', 'skill_load', 'skill_save', 'subagent',
];
// 平台控制工具豁免启用集（始终可用；仍受 preset 分级约束）
export const PLATFORM_EXEMPT = ['reload_platform', 'set_limits', 'plan_mode', 'exit_plan_mode'];
